FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update \
	&& apt-get install -y gcc \
	&& rm -rf /var/lib/apt/lists/* \
	&& pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]